// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCascader: typeof import('element-plus/es/el-cascader')['default']
    ElCheckbox: typeof import('element-plus/es/el-checkbox')['default']
    ElCheckboxGroup: typeof import('element-plus/es/el-checkbox-group')['default']
    ElDatePicker: typeof import('element-plus/es/el-date-picker')['default']
    ElForm: typeof import('element-plus/es/el-form')['default']
    ElFormItem: typeof import('element-plus/es/el-form-item')['default']
    ElInput: typeof import('element-plus/es/el-input')['default']
    ElInputNumber: typeof import('element-plus/es/el-input-number')['default']
    ElOption: typeof import('element-plus/es/el-option')['default']
    ElOptions: typeof import('element-plus/es/el-options')['default']
    ElRadio: typeof import('element-plus/es/el-radio')['default']
    ElRadioGroup: typeof import('element-plus/es/el-radio-group')['default']
    ElSelect: typeof import('element-plus/es/el-select')['default']
    ElSwitch: typeof import('element-plus/es/el-switch')['default']
    GForm: typeof import('./src/components/g-form/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
